config/routes.rb
CanvasApp::Application.routes.draw do

  # Root of Applications
  root to: 'static_pages#home'

  # Concerns
  concern :assignments do resources :assignments end
  concern :courses do resources :courses end
  concern :groups do resources :groups end
  concern :group_categories do resources :group_categories end
  concern :memberships do resources :memberships end
  concern :sections do resources :sections end
  concern :synced_groups do resources :synced_groups end
  concern :users do resources :users end

  # ActiveResource Routes
  resources :accounts, concerns: [:courses, :users]
  resources :assignments
  resources :courses do
    resources :groups
    resources :group_categories do 
      resources :groups, concerns: [:memberships, :users]
    end
    resources :assignments do
      resources :overrides
    end
    resources :sections, :users
  end
  resources :group_categories do
    resources :groups, concerns: [:memberships, :users] do 
      get 'export_csv', on: :collection
    end
    resources :users
  end
  resources :groups, concerns: [:memberships, :users]
  resources :users

  # Local synced group categories and groups
  resources :synced_group_categories, concerns: [:synced_groups]
  resources :synced_groups

  # Additional Routes
  # Appointment Groups
  resources :appointment_groups, :only => [:index, :show], concerns: [:users]
  match '/appointment_groups/pdf', to: 'appointment_groups#pdf', via: [:post]

  # User Related
  match '/users/masquerade',  to: 'users#masquerade', via: [:post]
  get   'user_search',        to: 'application#user_search'

  # Override Section Data
  match '/overrides/section_data', to: 'overrides#section_data', via: [:get]

end

app/models/account.rb
class Account < ApplicationModel
end

app/models/application_model.rb
class ApplicationModel < ActiveResource::Base
  self.site     = ENV["SITE_URL"]
  self.prefix   = '/api/v1/'
end

app/models/appointment_group.rb
class AppointmentGroup < ApplicationModel
end

app/models/assignment.rb
class Assignment < ApplicationModel
  self.prefix = '/api/v1/courses/:course_id/'
end

app/models/course.rb
class Course < ApplicationModel
  def save
    self.prefix = '/api/v1/accounts/:account_id/'
    prefix_options[:account_id] = account_id
    super
  end

end

app/models/enrollment.rb
class Enrollment < ApplicationModel
  self.prefix = '/api/v1/users/:user_id/'
end

app/models/group.rb
class Group < ApplicationModel
  def save
    self.site = '/api/v1/group_categories/:group_category_id/'

    prefix_options[:group_category_id]  = group_category_id
    prefix_options[:access_token]       = ENV["API_TOKEN"]
    super
  end
end

app/models/group_category.rb
class GroupCategory < ApplicationModel
end

app/models/membership.rb
class Membership < ApplicationModel
  self.prefix = '/api/v1/groups/:group_id/'
end

app/models/override.rb
class Override < ApplicationModel
  self.prefix = '/api/v1/courses/:course_id/assignments/:assignment_id/'

  def save
    prefix_options[:access_token] = ENV["API_TOKEN"]
    super
  end
end

app/models/section.rb
class Section < ApplicationModel
end

app/models/sub_account.rb
class SubAccount < ApplicationModel
  self.prefix = '/api/v1/accounts/:account_id/'
end

app/models/submission.rb
class Submission < ApplicationModel
  self.prefix = '/api/v1/courses/:course_id/assignments/:assignment_id/'
end

app/models/synced_group.rb
class SyncedGroup < ActiveRecord::Base
  attr_protected
  belongs_to :synced_group_category

  scope :by_group_id, -> { order("synced_groups.group_id ASC") }
end

app/models/user.rb
class User < ApplicationModel
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  # General check_paging resource
  def check_paging(collection, collection_array, resource, context, is_new)
    if is_new
      @collection_hash = Hash.new { |hash, key| hash[key] = Array.new }
    end
    unless collection.empty?
      @page += 1
      collection = context.get(resource.to_sym, :page => @page, :per_page => 10, :access_token => ENV["API_TOKEN"])
      collection_array << collection
      self.check_paging(collection, collection_array, resource, context, false)
    else
      collection_array = collection_array.flatten!
      @collection_hash[context.id] = collection_array
      return collection_array, @collection_hash
    end
  end

  # Different paging check for users
  # Depricate this when there's time
  def check_user_paging(users, context)
    options = {}
    if params[:group_category_id] && params[:unassigned]
      @options[:unassigned] = params[:unassigned]
    end
    unless users.empty?
      @page += 1
      @options[:page]     = @page
      @options[:per_page] = @per_page
      
      users = context.get(:users, @options)
      @user_array << users
      self.check_user_paging(users, context)
    else
      @user_array.flatten!
    end
  end

=begin
    # If the above code stops working, use the ActiveResource::ResourceNotFound rescue code below
    @page += 1
    begin 
      collection = context.get(resource.to_sym, :page => @page, :per_page => @per_page, :access_token => ENV["API_TOKEN"])
    rescue ActiveResource::ResourceNotFound
      collection_array = collection_array.flatten!
      @collection_hash[context.id] = collection_array
      return collection_array, @collection_hash
    else
      collection_array << collection
      self.check_paging(collection, collection_array, resource, context, false)
    end

    # If the above code stops working, use the ActiveResource::ResourceNotFound rescue code below
    @page += 1
    begin 
      options[:page]          = @page
      options[:per_page]      = @per_page
      options[:access_token]  = ENV["API_TOKEN"]
      users = context.get(:users, options)
    rescue ActiveResource::ResourceNotFound
      @user_array.flatten!
    else
      @user_array << users
      self.check_user_paging(users, context)
    end
=end

end

app/helpers/assignments_helper.rb
module AssignmentsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper

  def root_account
    account       = Account.find(:first, :params => { :access_token => ENV["API_TOKEN"] })
    root_account  = account.root_account_id.nil? ? account.id : nil
  end

  def perform_export(export_data=[])
    export_data ||= []
    groups, memberships = export_data

    export_file   = "groups_export_#{Time.now().strftime('%m-%d-%Y-%H%M%S')}.csv"
    @download_url = root_url + export_file

    CSV.open(Rails.root.join("public", export_file), "wb") do |csv|
      csv << ["Group Name", "Group ID", "User ID", "User Login", "User Full Name"]
      groups.each do |group|
        if memberships[group['id']].empty?
          csv << ["#{group['name']}", "#{group['id']}"]
        else
          memberships[group['id']].each do |member|
            profile_url = ENV["SITE_URL_CURL"] + "accounts/#{root_account}/users" + ENV["API_TOKEN_CURL"] + "&search_term=#{member['user_id']}"
            profile     = Curl::Easy.perform(profile_url)
            profile_results = JSON.parse(profile.body_str)
            csv << ["#{group['name']}", "#{group['id']}", "#{profile_results[0]['id']}", "#{profile_results[0]['login_id']}", "#{profile_results[0]['sortable_name']}"]
          end
        end
      end
    end 
  end

end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Canvas Web Apps at Wharton</title>
    <%= stylesheet_link_tag     "application", :media => "screen" %>
    <%= javascript_include_tag  "application" %>
    <%= render 'layouts/shim' %>
    <%= yield :head %>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <%= link_to "Wharton Courseware", root_path, class: "brand" %>
          <ul class="nav pull-right">

            <li class="divider-vertical"></li>
            <li>
              <% if session[:masquerade_as].nil? %>
                <%= form_tag("/users/masquerade", class: "form-inline pull-left") do %>
                  <div class="input-prepend">
                    <span class="add-on"><i class="fa fa-user"></i></span>
                    <%= text_field_tag(:user_id, nil, :placeholder => "Start typing user's name", class: "span3 masquerade-input sis_user_id") %>
                  </div>
                  <button type="submit" class="btn btn-inverse masquerade">Masquerade</button>
                <% end %>
              <% else %>
                <%= form_tag("/users/masquerade", class: "navbar-form pull-left") do %>
                  <button type="submit" class="btn btn-inverse stop-masquerade">Stop Masquerading</button>
                <% end %>
              <% end %>
            </li>
            <li class="divider-vertical"></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Canvas API Actions
                <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><a href=<%= appointment_groups_path %>><i class="fa fa-calendar"></i> Appointment Groups</a></li>
                <li class="divider"></li>
                <li><a href=<%= assignments_path %>> <i class="fa fa-list-alt"></i> Assignments</a></li>
                <li class="divider"></li>
                <li><a href=<%= synced_group_categories_path %>> <i class="fa fa-users"></i> Sync Sections as Groups</a></li>
              </ul>
            </li>
          </ul>
        </div> 
      </div>
    </div>

    <div id="content" class="container">
      <%= yield %>
    </div> 

    <div id="footer">
      <% if session[:masquerade_as] %>
        <div id="masquerade-info">
          <div class="alert alert-info">
            <i class="fa fa-exclamation-circle"></i> Masquerading as <strong><%= session[:masquerade_as] %></strong>
          </div>
        </div>
      <% end %>
    </div>

  </body>
</html> 

app/views/shared/_progress_bar.html.erb
<div class="progress progress-striped" style="display: none;">
  <div class="bar" style="width: 0%;"></div>
</div>

app/views/shared/_status_report.html.erb
<div class="alert alert-success status-report"></div>